### ISSUE TITLE
Use the native auto complete functionality of sublime

### ISSUE THREAD

**Issue by slifin** [zxqfl/tabnine-sublime#6]
Looks like this plugin is implemented using a tooltip

Here is an extension that overrides the inbuilt auto complete: https://github.com/alienhard/SublimeAllAutocomplete/blob/master/all_views_completions.py 
that allows using arrow keys and native theming is it possible to implement that here?

**Comment by zxqfl** [comment]
Reasons it is implemented this way:

- Latency
- Builtin autocomplete caches results but we need the editor to re-query TabNine each time a character is typed
- IIRC builtin autocomplete only gets triggered when you're typing a word

**Comment by pykong** [comment]
Although this issue is closed, I'd like to second @slifin in using arrow keys.
IMHO it is better to stick to the well known UX of the autocomplete instead of reinventing it anew.
I certainly speak for many other Sublime Text users that being able to cycle through the entries of the autocomplete is what is deeply ingrained into our muscle memories. Hence the lack thereof is irritating even if the offered alternative (namely jumping via `Tab + \d` is not that bad either.

Please bring back the cycling via arrow keys.

**Comment by zxqfl** [comment]
I can definitely add arrow key bindings. (I closed the issue because it was asking to use native autocompletion. But we can use arrow keys while keeping current popup.)

**Comment by nisanth074** [comment]
@zxqfl This'd be great. I had to uninstall TabNine because pressing the Tab key multiple times to cycle through suggestions is harder than cycling through suggestions by pressing the Up/Down arrow keys (and then pressing the Enter key to choose the right one). Also, unlike the native popup, TabNine's popup doesn't remain open while cycling through suggestions.

> I can definitely add arrow key bindings. (I closed the issue because it was asking to use native autocompletion. But we can use arrow keys while keeping current popup.)
